### ISSUE TITLE
Simulation is only on bottom left quarter

### ISSUE THREAD

**Issue by nutubogdan** [ccappelle/pyrosim#14]
After I updated my Mac, the simulation is only working on the bottom left corner and the rest of the screen is gray . Changing the size parameters in eval does not work
<img width="737" alt="pyrosim" src="https://user-images.githubusercontent.com/36013290/83052221-accdf880-a057-11ea-8444-1a3c60a1b46f.png">

**Comment by ccappelle** [comment]
First I want to note that I am not currently working on this repository and will not be updating it any further. You can check out a more up to date version here: https://github.com/mec-lab/pyrosim, however they may also not be updating it.

As for your specific issue, this probably has to do with retina displays and OpenGL viewport. I don't know the specific solution but the answer will probably be found by editing pyrosim/simulator/external/ode-0.12/drawstuff/src/osx.cpp. This file contains the specific drawing information on Mac computers. If you edit this file you will need to run build.sh each time to rebuild ODE. 

You can check out some more information about retina displays and OpenGL here: https://stackoverflow.com/questions/36672935/why-retina-screen-coordinate-value-is-twice-the-value-of-pixel-value

Hope this helps.
