### ISSUE TITLE
No sensor values from simulation

### ISSUE THREAD

**Issue by undera** [ccappelle/pyrosim#2]
I have tried to build a human-like robot shape, but stuck with simple
thing not working for me: no sensor data is reported after simulation
run. Even when I run something from demos (like this:
https://github.com/ccappelle/pyrosim/blob/master/demos/double-pendulum/dp-sensors.py),
it prints all zeros instead of actual sensor values.

Can you help me resolving this issue?

**Comment by ccappelle** [comment]
The first thing to try is to remake the c++ code using the make file in the 'simulator' directory. 
If that doesn't help can you provide the debug output that is printed out when you run the simulator. Also, do the graphics work when you run your code?

**Comment by undera** [comment]
I have taken clean source checkout, ran  `sh build.sh`, then ran `dp-sensors.py` demo. Still got no sensor data. I have attached the output of the console:
[dp-sensors.txt](https://github.com/ccappelle/pyrosim/files/1481349/dp-sensors.txt)

I am on Ubuntu 16.04

**Comment by undera** [comment]
I'm not very good at C++, I know python better. But I see `void NEURON::Print(void)` declared and never used. Maybe that's the problem...

**Comment by ccappelle** [comment]
`NEURON::Print(void)` is a leftover debugging statement from development so it shouldn't be printing anything out anyway. Over the past coupled of days I have changed some of the internal c++ code and maybe it no longer works correctly on linux. I will try it out and get back to you. In the mean time, what version of python are you using?

**Comment by undera** [comment]
I use Python 2.7.12

**Comment by undera** [comment]
I think I found it. It's `delete data` line in simulator.cpp

**Comment by ccappelle** [comment]
Again, while that line is misplaced, it actually shouldn't affect anything. I think the problem had to do with some changes I made to the print out process from the c++ code. I have reverted back to a previous commit so try pulling the changes and rerunning `sh build.sh`

**Comment by undera** [comment]
But I commented out that line and it fixed the issue. I pulled your changes before that and it did not fix the problem. I see your newer commits, gonna try it now.

**Comment by undera** [comment]
Confirmed, now I get the sensor data. Thanks for your help!

One feature request I have: is there any way to manipulate the simulation viewport size from Python? Something like `simulation.set_viewport_size(800, 600)` before `simulation.start()` would serve the need. Or as constructor parameter...

**Comment by ccappelle** [comment]
That should be easy to implement. I will let you know when it is done. I am closing this issue. Thank you for bringing this to my attention, everything was still working fine on my set up (Mac OSX)

**Comment by undera** [comment]
The new commits seem to work. Thank you very much, I love this project!
