### ISSUE TITLE
Evolve NEAT into PyRoSim

### ISSUE THREAD

**Issue by huchanwei123** [ccappelle/pyrosim#7]
Dear ccappelle,
I'm currently working on generalizing locomotion of modular robot using PyRoSim for simple algo. testing. My goal is to apply evolutionary algorithm (such as NEAT) on robot, and I'm wondering if I can reach the sensor data in simulation rather than after the whole simulation done. Can the user extracts sensor data at each time step?

Thanks!!

**Comment by ccappelle** [comment]
Within the c++ code you can access the sensor data at each time step but not from the python code. Pyrosim makes one batched send and one batched receive command where all the data is transferred. If you need to modify the simulation based on sensor values at each time step, you have to edit the c++ code.

**Comment by huchanwei123** [comment]
Got it! Seems that I need to dig deeper into ODE engine.
Thanks for the quick reply :)

**Comment by undera** [comment]
I have made a simple implementation of what you have asked @huchanwei123 
Check it out from my branch, and let's hope @ccappelle will accept the feature :)
